In [2]:
import numpy as np
array1 = np.zeros(3)
print(f'Array1 = {array1}')

array2 = np.zeros((1, 4))
print(f'Array2 = {array2}')

array3 = np.zeros((2, 5))
print(f'Array3 = {array3}')

Array1 = [0. 0. 0.]
Array2 = [[0. 0. 0. 0.]]
Array3 = [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
array1 = np.zeros(3)
array2 = np.zeros((1, 4))
array3 = np.zeros((2, 5))

print(array1[0], array1[2])
print(array2[0][0], array2[0][3])
print(array3[1][0], array3[1][3])

0.0 0.0
0.0 0.0
0.0 0.0


In [4]:
array1 = np.zeros(3)
array2 = np.zeros((1, 4))
array3 = np.zeros((2, 5))

print(type(array1))
print(type(array2))
print(type(array1[0]))
print(type(array2[0]))
print(type(array2[0][0]))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.float64'>
<class 'numpy.ndarray'>
<class 'numpy.float64'>


In [5]:
array1 = np.full((2, 4), 5)
print(array1)
array2 = np.full((1,5), 10)
# Here array2 is still a ndarray
print(array2)

array1 = np.full((2, 4), 5, dtype=int)
array1 = np.full((2, 4), 5, dtype=np.float64)

[[5 5 5 5]
 [5 5 5 5]]
[[10 10 10 10 10]]


In [6]:
arr = np.arange(1, 10)
print(arr, '\n')

# Reshape to 3x3 matrix
arr = arr.reshape(3, 3)
print(arr, '\n')

# Reshape back to the original size
arr = arr.reshape(9) # generates 1D array
print(arr)

arr = arr.reshape(1, 9) # generates 2D array
print(arr)

arr = arr.reshape(2, 5) # ValueError
print(arr)

[1 2 3 4 5 6 7 8 9] 

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5 6 7 8 9]]


ValueError: cannot reshape array of size 9 into shape (2,5)

In [7]:
matrix1 = np.array([[3, 4, 5], [2, 6, 9]])
matrix2 = np.array([[3, 4], [3, 5], [2, 6]])

matrix3 = np.dot(matrix1, matrix2)

print('Matrix3=\n', matrix3)

Matrix3=
 [[31 62]
 [42 92]]


In [8]:
matrix1 = np.array([[3, 3, 4], [2, 3, 9]])
matrix2 = np.array([[2, 5, 4], [2, 3, 19]])

sum_matrix = matrix1 + matrix2
difference_matrix = matrix1 - matrix2
product_matrix = matrix1 * matrix2
quotient_matrix = matrix1 / matrix2

print(sum_matrix)
print(difference_matrix)
print(product_matrix)
print(quotient_matrix)

[[ 5  8  8]
 [ 4  6 28]]
[[  1  -2   0]
 [  0   0 -10]]
[[  6  15  16]
 [  4   9 171]]
[[1.5        0.6        1.        ]
 [1.         1.         0.47368421]]
